TEA-12, TEA-31
eldarknz/team.project.praktikum.yandex pull request #12
Opened 2023-06-01 12:24 UTC by chelseajoint

Вёрстка главной страницы: мини-лендинг. 
Обновление кнопки на компонент кнопки в ошибках.

2023-06-01 18:55 UTC, DedStriger approved these changes

2023-06-01 19:09 UTC, DedStriger commented on packages/client/src/pages/Landing/Landing.tsx
> +    document.location = signInPath;
нужно сделать через useNavigation.
Иначе не произойдет навигации без перезагрузки

const navigate = useNavigation()
const handleSignInClick = useCallback(() => navigate(ROUTES.SignIn.path), [navigate])

2023-06-01 19:09 UTC, DedStriger commented on packages/client/src/pages/Landing/Landing.tsx
> +        <Button href={signUpPath}>
Не смотрел компонент Button, но если там просто ссылка, то надо или там тег a менять на NavLink. Или тут делать как писал выше

2023-06-01 19:09 UTC, DedStriger commented on packages/client/src/styles/index.scss
> +  background-image: url('https://images.unsplash.com/photo-1618022325802-7e5e732d97a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1348&q=80');
лучше скачать и импортить в tsx и вставлять через пропс  style

так как на удаленном сервере всегда могут просто удалить или заблочить ресурс

2023-06-01 21:26 UTC, lunaticenslaved requested changes

2023-06-01 21:26 UTC, lunaticenslaved commented on packages/client/src/pages/Landing/Landing.tsx
> +    document.location = signInPath;
Давай переделаем через `useNavigate` от react-router-dom?
Вот в документации https://reactrouter.com/en/main/hooks/use-navigate

Просто useNavigate будет делать навигацию пределах того же приложения, а изменение document.location заставляет браузер перейти к "новому" сайту, т.е. создавать и монтировать `<App />` еще раз, и, значит, сбросится стор и т.д.

2023-06-02 08:40 UTC, lunaticenslaved commented on packages/client/src/pages/Landing/Landing.tsx
> +        <Button href={signUpPath}>
Я завела задачу. Проверю Button и поменяю тег

2023-06-02 08:40 UTC, lunaticenslaved commented on packages/client/src/pages/Landing/Landing.tsx
> +        <Button href={signUpPath}>
> Не смотрел компонент Button, но если там просто ссылка, то надо или там тег a менять на NavLink. Или тут делать как писал выше

Я завела задачу. Проверю Button и поменяю тег

2023-06-02 08:41 UTC, lunaticenslaved approved these changes

2023-06-02 08:41 UTC, shbchk commented on packages/client/src/pages/Landing/Landing.tsx
> +        <Button href={signUpPath}>
Я уже меняю :)

2023-06-02 21:37 UTC, bin-umar commented
@chelseajoint привет! Я ревьюер из Я.Практикума, подскажи, пожалуйста, это точно самая весомая задача среди твоих? 
У меня есть сомнения.

> Индивидуальный зачёт
> К концу спринта вам необходимо отправить одну задачу из бэклога с наибольшей оценкой сложности на проверку > ревьюеру и получить от него апрув.

2023-06-02 22:43 UTC, chelseajoint commented
Привет @bin-umar.
Да, это точно :) В этом спринте, к сожалению или к счастью, у меня было всего две задачи и каждая из них имела оценку сложности один бал.
![Captura de pantalla 2023-06-03 a las 0 41 49](https://github.com/eldarknz/team.project.praktikum.yandex/assets/91132438/06e0da76-855f-4c71-a2bb-101592cb1f34)

2023-06-03 15:44 UTC, bin-umar approved these changes
В целом хотелось бы конечно чуть повысить сложность твоего ПР-а попросив переименовать названия классов в БЭМ, также исправить значения дизайн токенов, но ставлю аппрув только из соображений того что задача на один балл и фактически соответствует ею.
Но я бы очень порекомендовал исправить советуемые изменения так как они будут полезны как минимум для обучения и расширения спектра знаний, как максимум пригодятся в реальной работе.

2023-06-03 15:44 UTC, bin-umar commented on packages/client/src/styles/variables.scss
В этом файле не очень правильные название переменных. Например
- Чем отличается baseWhite от white? 
- В чём смысл наименовать переменные по названиям цветов? Ведь их также можно использовать напрямую и без переменных.

Основной смысл этих переменных это выделение цветов в дизайн-токены. А смысл дизайн токенов в том чтобы в случае редизайна или изменения конкретного значения токена изменился бы в одном месте.
То есть задача состоит не в том чтобы все белые цвета перевести в одну переменную, черные во вторую, и т.д. Потому что например мы можем использовать белый цвет как background, так и в качестве цвет текста основного наших кнопок. В таком случае совершенно валидно и правильно разделить их в две разные переменные:
- colorBg
- colorButtonText
Иными словами не стоит группировать по значению, так как это бессмысленно, а надо по css свойствам.

В качестве примера можешь посмотреть https://paradigm.mail.ru/design_tokens/colors, можешь на его примере убедиться что белый цвет например используется в трёх разных токенах.

Ну и в целом рекомендую прочитать про [дизайн-токенов](https://paradigm.mail.ru/design_tokens).

2023-06-03 15:44 UTC, bin-umar commented on packages/client/src/components/Error/Error.tsx
> +        className="basicButton basicButton--link"
Если уж решили наименовать классы вручную, то лучше их наименовать по [БЭМ](https://ru.bem.info/methodology/quick-start/)-у, в таком случае у вас будет чёткая структура и понимание как наименовать их. В данном примере будет правильнее называть `basicButton_link`, так как link это насколько я понял [модификатор](https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80).

2023-06-03 15:44 UTC, bin-umar commented on packages/client/src/components/Error/Error.tsx
> +import { useCallback } from 'react';
Лучше объединить
```suggestion
import React, { useCallback } from 'react';
```

2023-06-03 15:44 UTC, bin-umar commented on packages/client/src/pages/Landing/Landing.tsx
> +        <h1 className="landing--content---title">
По БЭМ-у:
```suggestion
      <div className="landing__content">
        <h1 className="landing__content__title">
```

2023-06-03 15:44 UTC, bin-umar commented on packages/client/src/styles/index.scss
> +  &--buttons-auth {
не стоит названия цветов привязать к структуре html-а

2023-06-03 16:46 UTC, merged

2023-06-03 18:02 UTC, bin-umar commented on packages/client/src/components/Error/Error.tsx
> +        className="basicButton basicButton--link"
@chelseajoint этот всё ещё не исправил :)

2023-06-03 18:06 UTC, bin-umar commented
@chelseajoint по возможности напиши пжл в ответах ок/не ок, это своего рода обратная связь, чтобы и нам было понятно дошёл ли информация/согласен ли ты с ним или нет, и т.д.

Про БЭМ имел ввиду весь проект, а не только твой ПР. Можешь обсудить с коллегами, мб сможете взять как отдельную задачу.

2023-06-03 18:09 UTC, koikonova commented
Хорошо, учту, спасибо :)
Да, я уже обсудила с некоторыми из них, но пока не изменили имена кнопок, тк они используются и в других частях программируемых моими коллегами которые пока в офлайне.