Tea 22
eldarknz/team.project.praktikum.yandex pull request #17
Opened 2023-06-03 06:09 UTC by DedStriger

Написал первую минимальную версию игры и документацию к ней

2023-06-03 21:23 UTC, lunaticenslaved approved these changes

2023-06-05 14:00 UTC, practicum-maxim-zyryanov requested changes
Начало хорошее, но есть много моментов, которые стоит лучше проработать. При этом, лучше сделать это сейчас, т.к. далее с этим кодом будет работать всё сложнее

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on docs/gameLogic.md
> +4. В случае прохождения уровня юзер попадает на страницу `/end?win=1` с возможностью рестарта
Хм, сразу возникает вопрос... а не сможет ли пользователь таким образом проходить уровни, просто вызывая `/end?win=1`?

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GenericObject/GenericObject.ts
> +}
Ход мысли отличный, но реализация спорная. По-хорошему, в интерфейсах вообще не следует определять свойства и большое число функций. Если есть здесь желание определить интерфейс, то следует объявить `Drawable`. В остальном текущий "интерфейс" скорее является абстрактным классом, плюс в отличии от интерфейса, тот позволит тебе сразу определить права доступа к свойствам.
```
interface Drawable {
  draw: () => void;
}

abstract class GenericObject implements Drawable {
  protected position: PlayerPosition;
  protected image: HTMLImageElement;
  protected width: number;
  protected height: number;

  abstract draw();
}
```

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +const diamand = createImage(diamandSrc);
Далее по коду сложно становится определить, что есть, например `hills` - представляется скорее набор объектов игры, но на деле имеем картинку, что совсем не очевидно. Если обратить внимание на саму картинку `hills.png`, то можно заметить ещё одну странность, т.к. такая картинка ожидаема для заставки, но не в качестве игрового объекта.

Что здесь можно предпринять?
1. Вместо `hills.png` завести `hill.png` с простым спрайтом.
2. Сделать холмы игровым объектом `Hill`
3. Рисовать холмы программно
4. Для картинок создать "менеджер" ресурсов, который позволит получать изображения по `images.hill`

Всё это позволит проще работать с логикой, и проще создавать новые уровни. А менеджер ресурсов не позволит забыть с чем работаешь.

Если есть необходимость создавать группы холмов, то можно на уровне параметра конструктора определять размер холма, но скорее всего этого не потребуется, достаточно просто несколько холмов рисовать рядом.

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +diamand.width = 50;
Т.к. `diamand` также некий игровой объект со своей логикой, то возможно он достоин того, чтобы и в коде у него появился класс, а это свойство отлично бы смотрелось в этом классе.

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +      });
Сейчас нормально, но призываю задуматься о нескольких вещах:

1. Несколько необычный набор параметров для игрока, т.к. `scrollOffset`, `canvas`, `context` это очень низкоуровневые детали, но решение проблемы больше лежит в архитектуре игры. К примеру, здесь можно обратиться к паттерну абстрактная фабрика / абстрактный метод. 
```
let game = new Game({scrollOffset, canvas, context});
let player = game.createPlayer();
```
2. `Player` тоже игровой объект, он также обладает методом `draw`, и если появятся враги, то едва ли он сильно будет от них отличаться. Рассмотри его как часть иерархии `GenericObject`

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +        }),
Здесь вызывают вопросы "магические числа", а также многословность и сложность конструкции. Если определим под каждый объект свой класс, то вполне сможем написать что-то такое:
```
let map = game.createMap();

map.add({ x: 0, y: 60 }, game.createPlatform()),
map.add({ x: 1000, y: 240}, game.createPlatform()),
map.add({ x: 1000, y: 60}, game.createPlatform()),
map.add({ x: 1500, y: 400}, game.createPlatform()),
map.add({ x: 2200, y: 400}, game.createPlatform()),
map.add({ x: 3200, y: 60}, game.createPlatform()),
map.add({ x: 4000, y: 200}, game.createPlatform()),
map.add({ x: 4400, y: 400}, game.createPlatform()),
map.add({ x: 4800, y: 600}, game.createPlatform()),
map.add({ x: 5089, y: 600}, game.createPlatform()),
map.add({ x: 5450, y:  750}), game.createFinish(),
```
Все повторяющиеся переменные скрыты в объектах, а описание карты стало более наглядным.

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +    );
Все подготовительные шаги рекомендую вынести в отдельный метод, чтобы не отвлекали от главного кода отрисовки

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +      : 0;
Если предполагать, что объекты из одной иерархии, то получили бы более единообразный код:
```
for (let item of map.items)
{
   item.update();
   item.draw();
}
```

Значения `5` и `-5` здесь магические числа, стоит вынести в константу, так проще понять, что это скорость, и легче в будущем поменять значение.

Кроме того, есть ощущение, что расчёт `velocity` это логика объекта. Стоит переместить её в класс `PlayerImpl`, а возможно даже в метод `update`

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +      });
Это очень сложно, и вновь какие-то магические числа, но можно разбить на части, завести константы и вынести отдельные функцию:
```
let {x , y} = this.player.position;
let {velocity, speed} = player;

if (this.keys.right.presed) {
	if (x <= MAX_SIZE) {
		velocity.x = speed;
		return;
	}
} else {
	if (x > MIN_SIZE || (x > 0 && this.scrollOffset === 0) {
	    velocity.x = -speed;
		return;
	}
}

velocity.x = 0;
if (this.keys.right.presed)
	this.scrollOffset += speed;
else if (this.keys.left.presed && this.scrollOffset > 0)
	this.scrollOffset -= speed;

this.player.scrollOffset = this.scrollOffset;

this.platforms.forEach(platform => {
    // а здесь вновь повторяется логика выше, ох чувствую тут стоит вынести логику в функцию
	if (this.keys.right.presed) {
		platform.position.x -= this.player!.speed;
	} else if (this.keys.left.presed && this.scrollOffset > 0) {
		platform.position.x += this.player!.speed;
	}
)
```

Обрати внимание, что мой код здесь далёк от совершенства, он лишь для иллюстрации. Здесь есть куда больше возможностей для упрощения кода, подумай в этом направлении

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +    });
Здесь замечания аналогичные

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +    }
Логика не соответствует описанию. Получается игра заканчивается не из-за драгоценного камня, а из-за конца карты.

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/Player/Player.ts
> +}
Здесь имеем не интерфейс, не абстрактный класс, а скорее всего обычный класс

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/Player/PlayerImpl.ts
> +  sprites: Player['sprites'];
Очень не нравится два момента: (1) определение значений через квадратные скобки, т.к. легко допустить ошибку в строке; (2) и в целом такое определение на уровне объявления класса;

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/Player/PlayerImpl.ts
> +    }
И вновь сложно, и вновь магические числа

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/Game.tsx
> +      logic.animate();
Логику стоит вынести на уровень класса игры, задача компонента здесь максимум элемент канваса получить и передать его игре.

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/Game.tsx
> +    };
Есть ощущение, что конструкция избыточна и можно упростить

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/view/GameView.module.scss
> +}
Не ясно зачем потребовались вычисления

2023-06-05 14:00 UTC, practicum-maxim-zyryanov commented on packages/client/src/utils/getMovePlayerCondition.ts
> +};
И вновь можно упростить

2023-06-06 10:02 UTC, DedStriger commented on docs/gameLogic.md
> +4. В случае прохождения уровня юзер попадает на страницу `/end?win=1` с возможностью рестарта
перенес в стейт при переходе между страницами

2023-06-06 10:02 UTC, DedStriger commented on packages/client/src/core/GenericObject/GenericObject.ts
> +}
убрал

2023-06-06 10:02 UTC, DedStriger commented on packages/client/src/core/GameLogic/GameLogic.ts
> +const diamand = createImage(diamandSrc);
необходимости нет, это просто декорации. Красота ради красоты

2023-06-06 10:03 UTC, DedStriger commented on packages/client/src/core/GameLogic/GameLogic.ts
> +diamand.width = 50;
Это не нужная строка, забыл ее удалить. Удалил сейчас

2023-06-06 10:05 UTC, DedStriger commented on packages/client/src/core/GameLogic/GameLogic.ts
> +      });
1. По идее можно добавлять игроков и что-то вроде гонок устраивать. Но пока думаем надо или нет
2. у них разный метод draw

2023-06-06 10:06 UTC, DedStriger commented on packages/client/src/core/GameLogic/GameLogic.ts
> +        }),
Там будет 10 уровней с рандомным размешением. И надо будет писать код для генерации уровней. Это решили на следующий спринт вынести

2023-06-06 10:06 UTC, DedStriger commented on packages/client/src/core/GameLogic/GameLogic.ts
> +    );
Поправил

2023-06-06 10:06 UTC, DedStriger commented on packages/client/src/core/GameLogic/GameLogic.ts
> +      : 0;
Поправил

2023-06-06 10:06 UTC, DedStriger commented on packages/client/src/core/GameLogic/GameLogic.ts
> +      });
Попытался упростить, вроде по лучше стало

2023-06-06 10:07 UTC, DedStriger commented on packages/client/src/core/GameLogic/GameLogic.ts
> +    });
упростил

2023-06-06 10:07 UTC, DedStriger commented on packages/client/src/core/GameLogic/GameLogic.ts
> +    }
Поправил логику, теперь надо именно в кристал телом запрыгнуть

2023-06-06 10:07 UTC, DedStriger commented on packages/client/src/core/Player/Player.ts
> +}
убрал

2023-06-06 10:07 UTC, DedStriger commented on packages/client/src/core/Player/PlayerImpl.ts
> +  sprites: Player['sprites'];
убрал

2023-06-06 10:08 UTC, DedStriger commented on packages/client/src/core/Player/PlayerImpl.ts
> +    }
вынес в константы, но тут тяжело что-то упростить

2023-06-06 10:08 UTC, DedStriger commented on packages/client/src/pages/Game/Game.tsx
> +    };
не знаю как тут переписать. Надо ведь чтобы слушатели убирались на unmount

2023-06-06 10:09 UTC, DedStriger commented on packages/client/src/pages/Game/view/GameView.module.scss
> +}
чтобы игра не пересекала хедр шаблона

2023-06-06 10:10 UTC, DedStriger commented on packages/client/src/utils/getMovePlayerCondition.ts
> +};
упростил

2023-06-07 11:05 UTC, practicum-maxim-zyryanov commented on packages/client/src/core/GameLogic/GameLogic.ts
> +      });
Общая иерархия классов не запрещает нам иметь разную реализацию, она лишь дополнительно позволяет их подогнать под общий интерфейс. К примеру:
```
abstract class GameObject {
   constructor(private canvas, private x, private y) {  }

   abstract draw();
}

class Platform extends GameObject {
   private width = 100;
   private height = 10;
  
   draw() {
       this.canvas.rect(x, y, width, height)
   }
}

class Player extends GameObject {
   private width = 10;
   private height = 10;
  
   draw() {
       this.canvas.rect(x, y, width, height)
       // и прочий код по отрисовке
   }

   move() {
      // специфичный код для игрока, например x += 5;
   }
}

let player = new Player(canvas, 10, 0);
let platforms = [];

for (let i = 0; i < 10; i++)
  platforms.push(new Platform(canvas, 100 * i,  2 * i)

let map: GameObject[] = [...platforms, player];

// И здесь теперь имеем доступ и игроку, и к платформам
// но при этом отрисовку всех объектов можно вызвать не учитывая конечный тип

map.forEach(i => i.draw())

```

Метод draw здесь будет вызван для каждого объекта тот, который у реального класса, а не общий объявленный в GameObject

2023-06-08 06:57 UTC, practicum-maxim-zyryanov approved these changes
Большая часть замечаний исправлена, по другой части могу понять твою позицию. Поскольку ничего нового не бросилось в глаза, то даю Approve. Но прошу в процессе последующей проработки игры побороться со сложностью, т.к. сейчас пробираться через хитросплетение условий весьма тяжело.

2023-06-08 09:21 UTC, merged