Страница логина + логика авторизации [TEA-18]
eldarknz/team.project.praktikum.yandex pull request #22
Opened 2023-06-04 13:41 UTC by shbchk

[video-convert-1685885792896.webm](https://github.com/eldarknz/team.project.praktikum.yandex/assets/12234507/8a871bd4-767f-4e28-af0b-7562adddec43)

_Задача также включает в себя подзадачи: 
› Кнопки и инпут: https://github.com/eldarknz/team.project.praktikum.yandex/pull/6
› Верстка страницы логина: https://github.com/eldarknz/team.project.praktikum.yandex/pull/13
› Валидация: https://github.com/eldarknz/team.project.praktikum.yandex/pull/18_

2023-06-04 13:50 UTC, DedStriger approved these changes

2023-06-05 19:13 UTC, bin-umar commented on packages/client/src/api/BaseAPI.ts
> +  };
Не стоит из одних константов сделать класс, их можно сохранить в виде обычной константы.

2023-06-05 19:17 UTC, bin-umar requested changes
Привет!

У вас кажется большой рассинхрон получился, твоя коллега в соседном ПР сделал хорошую архитектуру для форм и HTTPTransport для сетевых запросов. Тебе стоит интегрироваться с ним (ПР),  так как при мерже будет конфликт файлов и решений.

2023-06-05 19:17 UTC, bin-umar commented on packages/client/src/api/BaseAPI.ts
Тебе надо интегрироваться с https://github.com/eldarknz/team.project.praktikum.yandex/pull/20/files и использовать HTTPTransport.ts вместо него

2023-06-06 06:47 UTC, shbchk commented on packages/client/src/api/BaseAPI.ts
Привет, Джахонгир! А можешь, пожалуйста, объяснить, почему надо использовать HTTPTransport здесь? Я не понимаю, не вижу преимуществ. Зачем делать какую-то надстройку над fetch?

```
import {HTTPTransport} from './somepath'

HTTPTransport.get('somepath')
```

Эта конструкция не то чтобы удобнее, чем `fetch('somepath')`, но при этом теряется возможность настройки.

В методе `HTTPTransport.post()` сейчас жестко зашит JSON-хедер, а если мне нужно будет отправить другой хедер? Придется переписывать HTTPTransport, пробрасывать в него другие хедеры. Какой смысл, если можно просто воспользоваться тем же самым fetch, не придумывая для него прослоек?

2023-06-06 09:55 UTC, bin-umar commented on packages/client/src/api/BaseAPI.ts
Для сетевых запросов вам нужно в любом случае нужна определённая точка входа через которого можно будет настроить все желанные настройки. Многие ребята не парятся этим и просто берут axios в котором даётся такая возможность конфигурации.

Когда у вас в проекте 5-10 запросов необходимость небольшого такого модула может и не ощущаться, но отправлять везде через голый fetch это дублирование одного и того ж кода. Например вам может понадобиться добавить опцию `mode: cors`, а у вас в проекте уже 20 фетч запросов, везде будете добавлять их?  Или `credentials: 'include'` (это точно вам понадобиться), или какой нибудь общий `header`. 
Поэтому как говорю выше, вам в любом случае нужна будет модуль какой нибудь. В вашем случае HTTPTransport, который очевидно в недоделенном виде чтобы отвечать за все потребности, но лучше чем BaseAPI, и в ней заложены правильные шаги начало модуля. Например то что ты говоришь что хедер жёстко защит, это проблема реализации а не самого модула, если вам она не нравится, придите с коллегами в консенсус, и реализуйте его. Ничего страшного в начале его по мере необходимости дотюнит, у вас не стоит задача сделать его сразу в идеальном виде.

Другой кейс почему такой модуль важен, например вам завтра захочется всё ж использовать тот ж axios, то вы легко сможете заменить эти методы из fetch на axios. Большого рефакторинга не требуется.

2023-06-06 10:00 UTC, bin-umar commented on packages/client/src/api/BaseAPI.ts
В качестве примера можете посмотреть пример других ребят https://github.com/fastPaws-game/fastPaws/blob/main/packages/client/src/utils/fetchApi.tsx

Или https://github.com/frontend-park-mail-ru/2019_1_SleeplessNights/blob/master/public/app/modules/ajax.js , ещё года четыре назад когда я сам учился в подобном образовательном проекте, не в идеальном состоянии конечно, но как пример как должен выглядит модуль этот, можете посмотреть.

2023-06-06 13:09 UTC, shbchk commented
Добавил HTTPTransport, а интеграцию компонента формы придется оставить уже на следующий спринт

2023-06-06 16:22 UTC, bin-umar commented
> Добавил HTTPTransport, а интеграцию компонента формы придется оставить уже на следующий спринт

@shbchk Почему придётся?

2023-06-06 16:26 UTC, shbchk commented
Потому что PR с компонентом формы еще не смержен

2023-06-06 16:43 UTC, bin-umar commented
@shbchk есть какие-то блокеры для того чтобы его смёржит?

2023-06-06 16:49 UTC, shbchk commented
@bin-umar только время членов команды — все работают в разное время. Есть ли какие-то блокеры, чтобы заапрувить этот PR, не дожидаясь интеграции компонента, написанного другим членом команды? :)

2023-06-06 16:52 UTC, bin-umar commented
@shbchk в целом нет, просто хотелось бы увидеть уже в конечном виде. Сейчас посмотрю ещё раз.

2023-06-06 16:55 UTC, shbchk commented
Да, отлично понимаю! Но увы, я пока не могу предсказать, когда тот PR будет смержен и когда я смогу добраться до его интеграции, а получить апрув уже хочется - чтобы двигаться дальше

2023-06-06 16:55 UTC, bin-umar commented on packages/client/src/components/AuthForm/AuthForm.tsx
> +          if (value && value.reason) {
```suggestion
          if (value?.reason) {
```

2023-06-06 17:07 UTC, bin-umar commented on packages/client/src/components/AuthForm/AuthForm.tsx
Лучше разделить логику signUp и signIn. Потому что со временем их код может возрастать, соответственно и текущий файл. Атомарные компоненты читабельнее и имеют менее когнитивную сложность.

SignUp.tsx и SignIn.tsx идеальное место для них.

2023-06-06 17:07 UTC, bin-umar commented on packages/client/src/api/AuthAPI.ts
> +    this.http = new HTTPTransport();
`HTTPTransport` лучше было бы сделать синглтоном, так как нет причин сделать обратное, наоборот добавляет лишний память в приложении.

2023-06-06 17:07 UTC, bin-umar commented on packages/client/src/api/AuthAPI.ts
>        body: JSON.stringify(data),
Давай попробуем перенести `JSON.stringify` в `HTTPTransport`

2023-06-06 17:07 UTC, bin-umar commented on packages/client/src/api/AuthAPI.ts
> +      url: API_URL + '/signup',
```suggestion
      url: `${API_URL}/signup`,
```

2023-06-06 17:07 UTC, bin-umar commented on packages/client/src/controllers/AuthController.ts
> +        return response.json();
Это тоже лучше перенести в `HTTPTransport`, как я показал в примере.

2023-06-06 17:07 UTC, bin-umar commented on packages/client/src/controllers/AuthController.ts
> +        return json;
Этот обработчик нужен чтобы просто в консоль печатать ответ?

2023-06-06 17:07 UTC, bin-umar commented on packages/client/src/core/HTTPTransport.ts
> +    body?: BodyInit | null;
Какой body может быть гет запроса?

2023-06-06 17:09 UTC, bin-umar approved these changes
Ставлю аппрув чтобы не блокировались мною, но рекомендую доработать HTTPTransport добавляя советуемые замечания. Его необходимость и пользу я уже подробнее тебе написал.

2023-06-06 17:12 UTC, shbchk commented
Спасибо, Джахонгир! Обязательно доработаем в лучшем виде :)

2023-06-06 17:13 UTC, shbchk commented on packages/client/src/controllers/AuthController.ts
> +        return json;
Да, временная штука здесь

2023-06-06 17:14 UTC, shbchk commented on packages/client/src/api/AuthAPI.ts
> +    this.http = new HTTPTransport();
Ага, сделаем

2023-06-06 17:14 UTC, shbchk commented on packages/client/src/components/AuthForm/AuthForm.tsx
Принято!

2023-06-07 10:30 UTC, merged