TEA-55
eldarknz/team.project.praktikum.yandex pull request #35
Opened 2023-06-16 14:30 UTC by chelseajoint

Написание тестов для игрового движка и аторизации

2023-06-16 18:45 UTC, lunaticenslaved commented on packages/client/src/components/AuthForm/AuthForm.test.tsx
> +        'Кажется, вы ошиблись в адресе 😱 Пожалуйста, перепроверьте еще раз!'
У нас есть класс валидатора в src/service/Validate.ts. Давай ошибки оттуда использовать, чтобы тесты не падали, если текст будем менять?

```
const validate = new Validate();
screen.getByText(validate.errorMessages.name);
```

2023-06-16 18:46 UTC, chelseajoint commented on packages/client/src/components/AuthForm/AuthForm.test.tsx
> +        'Кажется, вы ошиблись в адресе 😱 Пожалуйста, перепроверьте еще раз!'
ок, спасибо, исправлю :)

2023-06-16 18:48 UTC, lunaticenslaved commented on packages/client/src/components/AuthForm/AuthForm.test.tsx
> +        'Кажется, вы ошиблись в адресе 😱 Пожалуйста, перепроверьте еще раз!'
Где можно, конечно. Например, `'Пароли не совпадают'` в валидаторе нет.
Можно тогда оставить как есть, либо добавить в errorMessages ещё одно сообщение.

2023-06-16 19:20 UTC, lunaticenslaved approved these changes

2023-06-17 07:14 UTC, Olegas approved these changes

2023-06-17 07:24 UTC, Olegas requested changes
Не сливайте пока пожалуйста, по ошибке нажал approve. Еще пока в процессе...

2023-06-17 07:33 UTC, Olegas requested changes

2023-06-17 07:33 UTC, Olegas commented on packages/client/src/components/AuthForm/AuthForm.test.tsx
> +);
В этих тестах проверили что форма рисуется и проверяет поля - это правильно.
Но одна из важных частей формы регистрации/авторизации это то, что она отправляет запрос с введенными данными. Надо это тоже проверить

2023-06-17 07:33 UTC, Olegas commented on packages/client/src/core/GameLogic/GameLogic.test.tsx
> +describe('GameLogic', () => {
В тесты игровой логики точно стоит добавить тесты на завершение игры - проверку условий выигрыша/проигрыша.

2023-06-18 08:20 UTC, chelseajoint commented on packages/client/src/components/AuthForm/AuthForm.test.tsx
> +);
Привет Олег,
Спасибо за ревью)
Добавила пару тестов, но к сожалению, они не проходят и не могу понять почему :( 
Была бы очень признательна твоей помощи, может можешь подсказать в чем проблема?
Заранее огромное спасибо!

2023-06-18 08:21 UTC, chelseajoint commented on packages/client/src/core/GameLogic/GameLogic.test.tsx
> +describe('GameLogic', () => {
Тут такая же история, добавила два теста. На проигрыш проходит, выигрыш зависает =(

2023-06-18 08:32 UTC, Olegas commented on packages/client/src/components/AuthForm/AuthForm.test.tsx
> +);
@chelseajoint ок, я гляну

2023-06-18 17:00 UTC, Olegas commented on packages/client/src/components/AuthForm/AuthForm.test.tsx
> +);
@chelseajoint а ты пробовала через отладчик пройтись и понять, что не так? Я посмотрел - тесты не зависают, они просто не проходят. Потому что не выполняется условие выигрыша. В функции _getWinCondition только одно из четырех условий равно true. Остальные false. То есть тест падает совершенно законно.

Возьми IDE, запусти тест под отладкой и пройди по шагам, посмотри что не так. Может какие-то начальные условия не заданы?

2023-06-18 22:03 UTC, chelseajoint commented on packages/client/src/components/AuthForm/AuthForm.test.tsx
> +);
Хорошо, спасибо огромное @Olegas ^^

2023-06-24 18:20 UTC, Olegas requested changes
В PR появилось куча изменений, не связанных с задачей (реализация тестов).
Кажется были удалены файлы, которые не должны быть удалены (sw.js например)
Сделайте пожалуйста что бы в PR были только изменения, относящиеся к задаче, которую вы несете на ревью

2023-06-24 22:34 UTC, chelseajoint commented
Привет @Olegas 
А можно мне подсказку как это сделать? 
Изначально я просто обновила ветку чтобы не было конфликтов и поэтому появилось столько изменений, но как вернутся к исходному варианту не понимаю. git revert не срабатывает или я что-то делаю не так.

2023-06-25 07:07 UTC, closed without merging

2023-06-25 07:39 UTC, Olegas commented
> Привет @Olegas А можно мне подсказку как это сделать? Изначально я просто обновила ветку чтобы не было конфликтов и поэтому появилось столько изменений, но как вернутся к исходному варианту не понимаю. git revert не срабатывает или я что-то делаю не так.

@chelseajoint я бы взял только те коммиты, которые относятся к задаче, и перенес их на текущую актуальную голову ветки "dev"
Еще, судя по тому что в твоей ветке некоторые файлы удалены (например sw.js - я не думаю что вы вдруг решили удалить service worker в dev ветке) ты, возможно, решила конфликты "не в ту сторону"

2023-06-25 07:42 UTC, chelseajoint commented
Привет @Olegas 
Спасибо за ответ :) В итоге я так и не разобралась с этим и решила создать новый PR.
https://github.com/eldarknz/team.project.praktikum.yandex/pull/38
Отправила его на проверку.