Kanzafarover/tea 53 adding web api
eldarknz/team.project.praktikum.yandex pull request #36
Opened 2023-06-20 14:43 UTC by eldarknz

### Какую задачу решаем
Добавляем возможность игры в полноэкранном режиме

### Скриншоты/видяшка (если есть)
До нажатия кнопки Enter
<img width="1800" alt="Снимок экрана 2023-06-20 в 17 41 06" src="https://github.com/eldarknz/team.project.praktikum.yandex/assets/28821969/680917ac-cb8b-4465-8dad-0cdeb2816543">

После нажатия кнопки Entrer
<img width="1800" alt="Снимок экрана 2023-06-20 в 17 41 21" src="https://github.com/eldarknz/team.project.praktikum.yandex/assets/28821969/b26880cb-cf0e-497b-8aea-c539e664aa2f">

### TBD (если есть)

2023-06-20 14:49 UTC, koikonova approved these changes

2023-06-20 20:02 UTC, Olegas requested changes
Есть замечания по коду, нужно доработать

2023-06-20 20:02 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
> +        if (ref) {
Тут не нужна проверка, потому что ты уже проверил выше наличие ref

2023-06-20 20:02 UTC, Olegas commented on packages/client/src/utils/fullscreen.ts
> +      toggleFullscreen(document.documentElement);
Это не опечатка, что тут весь документ? Я думал canvas сюда передается для того что бы именно его вывести на полный экран.

2023-06-20 20:02 UTC, Olegas commented on packages/client/src/utils/fullscreen.ts
> +const exitFullScreen = (
Если для выхода из полноэкранного режима всегда нужен document, зачем его передавать через аргументы?

2023-06-20 20:02 UTC, Olegas commented on packages/client/src/utils/fullscreen.ts
> +interface DocumentElementWithFullscreen
Дважды определен интерфейс DocumentElementWithFullscreen

2023-06-21 10:37 UTC, eldarknz commented on packages/client/src/utils/fullscreen.ts
> +interface DocumentElementWithFullscreen
Исправил

2023-06-21 10:38 UTC, eldarknz commented on packages/client/src/utils/fullscreen.ts
> +const exitFullScreen = (
Исправил. Не знал, что выход из полноэкранного режима всегда применяется ко всему document.

2023-06-21 10:43 UTC, eldarknz commented on packages/client/src/utils/fullscreen.ts
> +      toggleFullscreen(document.documentElement);
Да, на данный момент необходимо передать document.documentElement, для корректного отображения игры, но это временное решение, т.к. верстка игры не позволяет корректно отображать игру в полноэкранном режиме, пропадает фон и хэдер сверху справа, это надо будет поправить в отдельной задаче и тогда уже toggleFullscreen будем передавать canvas.

2023-06-21 10:43 UTC, eldarknz commented on packages/client/src/pages/Game/Game.tsx
> +        if (ref) {
Исправил

2023-06-21 17:48 UTC, Olegas approved these changes

2023-06-23 18:33 UTC, merged