Add Yandex OAuth [TEA-70]
eldarknz/team.project.praktikum.yandex pull request #39
Opened 2023-07-01 17:35 UTC by lunaticenslaved

Добавила OAuth авторизацию.

[recording (8).webm](https://github.com/eldarknz/team.project.praktikum.yandex/assets/54212063/6b2f5622-26d1-41ab-8360-d44d3600c8df)

2023-07-03 07:46 UTC, DedStriger commented on packages/client/src/App.tsx
> +  }, []);
выглядит как мертвый код (я про пустой эффект). Или так надо?

2023-07-03 07:46 UTC, DedStriger commented on packages/client/src/App.tsx
> +    })();
IIFE тут странно выглядит, кажется такое в мидлвары выносят, но могу ошибаться

2023-07-03 18:36 UTC, lunaticenslaved commented on packages/client/src/App.tsx
> +    })();
Можешь пример скинуть?

2023-07-03 18:37 UTC, lunaticenslaved commented on packages/client/src/App.tsx
> +  }, []);
Нет, так не надо. Уберу

2023-07-04 17:09 UTC, DedStriger approved these changes

2023-07-04 20:11 UTC, IvanPeleshok commented on packages/client/src/App.tsx
> +  return !isLoadingViewer ? (
Предлагаю переписать с красивым форматированием:
```
isLoadingViewer 
  ? <PageLoader withBackground />
  : (
    <BrowserRouter>
      <Router />
    </BrowserRouter>
  )
```

2023-07-04 20:14 UTC, IvanPeleshok commented on packages/client/src/components/AuthForm/AuthForm.tsx
> +    useCallback(
Немного странное форматирование получается, предлагаю переписать на что-то такое:
```
useCallback(e => {
  e.preventDefault()
  controllers.auth.signinwithYandex()
}, [controllers.auth]
```

2023-07-04 20:16 UTC, IvanPeleshok commented on packages/client/src/hooks/useViewerFromSession.ts
> +    await controllers.auth.getUserFromOAuth();
Возможно есть смысл подумать о том, чтобы oAuth вынести на уровень redux (редакс санки), придерживаясь единого стиля к взаимодействию с данными

2023-07-04 20:18 UTC, IvanPeleshok requested changes
Есть небольшие замечания

2023-07-05 15:28 UTC, lunaticenslaved commented on packages/client/src/components/AuthForm/AuthForm.tsx
> +    useCallback(
> Немного странное форматирование получается, предлагаю переписать на что-то такое:

Прости, немного не поняла о чем речь.
Если о том, как расставлены переносы строк, то у нас так настройки форматирования выставлены :(

2023-07-05 15:43 UTC, lunaticenslaved commented on packages/client/src/App.tsx
> +  return !isLoadingViewer ? (
> В дальнейшем придерживаться такого написания тернарников в JSX

Имеется ввиду negated condition?

2023-07-06 08:44 UTC, IvanPeleshok commented on packages/client/src/App.tsx
> +  return !isLoadingViewer ? (
Имелось ввиду и форматирование таких тернарных выражений, и то что isLoadingViewer с отрицанием выглядело избыточным

2023-07-06 08:45 UTC, IvanPeleshok commented on packages/client/src/components/AuthForm/AuthForm.tsx
> +    useCallback(
Вы его как-то видоизменяли правила? 
Не встречал в практикуме никогда, чтобы форматирование такого вида было обязательным

2023-07-06 19:09 UTC, lunaticenslaved commented on packages/client/src/components/AuthForm/AuthForm.tsx
> +    useCallback(
> Вы изменяли правила?

Хм, даже не знаю. В единственном коммите в ветке main стоит ширина строки в 50 символов. 

https://github.com/eldarknz/team.project.praktikum.yandex/blob/main/.prettierrc#L6

2023-07-06 22:08 UTC, IvanPeleshok commented on packages/client/src/components/AuthForm/AuthForm.tsx
> +    useCallback(
@lunaticenslaved, оки, отправляй PR на ревью, апрувну :)

2023-07-06 22:08 UTC, IvanPeleshok approved these changes

2023-07-07 10:31 UTC, IvanPeleshok commented
@lunaticenslaved, привет
Переведи задачку в статус ревью, апрувну :)

2023-07-10 07:09 UTC, merged