Kanzafarover/tea 68 add more web api
eldarknz/team.project.praktikum.yandex pull request #57
Opened 2023-07-22 12:51 UTC by eldarknz

### Какую задачу решаем
Используя Web Audio API добавлены звуки:
- нажатие клавиш вперед, назад, прыжок
- успешное прохождение уровня
- окончание игры при падении персонажа с платформ

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-22 12:55 UTC, chelseajoint approved these changes

2023-07-22 16:50 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду. Написал их в комментарии.
Нужно доработать.

2023-07-22 16:50 UTC, Olegas commented on packages/client/src/core/GameAudio/GameAudio.ts
> +    }
Для каждого звука у вас повторяется одна и та же последовательность действий.
Если нету - создать. Выставить громкость, запустить или сбросить время в 0.
Получилась копипаста. Надо выделить какой-то общий метод и просто параметризовать его.

2023-07-22 22:24 UTC, eldarknz commented on packages/client/src/core/GameAudio/GameAudio.ts
> +    }
Вынес в отдельный метод.

2023-07-23 07:24 UTC, Olegas requested changes
Вот этот участок
```
    if (volume <= 0.01) return;
    if (!this.jumpSound) {
      this.jumpSound = createAudio(jump);
    }
    this.jumpSound.volume = volume;
```
По прежнему повторяется для каждого звука

2023-07-23 10:21 UTC, eldarknz commented
> Вот этот участок
> 
> ```
>     if (volume <= 0.01) return;
>     if (!this.jumpSound) {
>       this.jumpSound = createAudio(jump);
>     }
>     this.jumpSound.volume = volume;
> ```
> 
> По прежнему повторяется для каждого звука

Исправил

2023-07-23 10:34 UTC, Olegas approved these changes

2023-07-23 12:22 UTC, merged